# Following https://docs.docker.com/get-started/workshop/04_sharing_app/
# After docker push zweknu/spellingbee, apply this
# Then kubectl port-forward --address=0.0.0.0 svc/spellingbee-entrypoint 3000:3000
apiVersion: apps/v1
kind: Deployment
metadata:
   name: spellingbee-grpc
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         spellingbee: web
   template:
      metadata:
         labels:
            spellingbee: web
      spec:
         securityContext:
            # nobody:nogroup
            runAsUser: 65534
            runAsGroup: 65534
         containers:
            - name: spellingbee-server
              image: docker.io/zweknu/spellingbee
              resources:
                 limits:
                    memory: "128Mi"    
                    cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
   name: spellingbee-entrypoint
   namespace: default
spec:
   type: NodePort
   selector:
      spellingbee: web
   ports:
      - port: 3000
        name: grpc
        targetPort: 3000
      - port: 3001
        name: web
        targetPort: 3001
