# Or use the helm chart in ../helm/spellingbee.
apiVersion: apps/v1
kind: Deployment
metadata:
   name: spellingbee
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         spellingbee: web
   template:
      metadata:
         labels:
            spellingbee: web
      spec:
         securityContext:
            # nobody:nogroup
            runAsUser: 65534
            runAsGroup: 65534
         containers:
            - name: spellingbee
              image: docker.io/zweknu/spellingbee
              resources:
                 limits:
                    memory: "128Mi"    
                    cpu: "1"

---
# You'll need Cloud Provider KIND
# (https://kind.sigs.k8s.io/docs/user/loadbalancer/) if you want a
# loadbalancer.
apiVersion: v1
kind: Service
metadata:
   name: spellingbee
   namespace: default
spec:
   type: LoadBalancer
   selector:
      spellingbee: web
   ports:
      - port: 3000
        name: grpc
        targetPort: 3000
      - port: 3001
        name: web
        targetPort: 3001
